`ifndef TICK_REGISTER_CONSTANTS_V
`define TICK_REGISTER_CONSTANTS_V

`define TICK_REGISTER_MODE_DEF 2'h0
`define TICK_REGISTER_MODE_INC 2'h1
`define TICK_REGISTER_MODE_DEC 2'h2
`define TICK_REGISTER_MODE_SET 2'h3

`endif // TICK_REGISTER_CONSTANTS_V
