# rules for building formal verification

FORMAL_DOCKER_PREFIX=docker run --rm -v $(PWD):/src --workdir /src
FORMAL_DOCKER_IMAGE=davidsiaw/ocs
FORMAL_CMD_PREFIX=$(FORMAL_DOCKER_PREFIX) $(FORMAL_DOCKER_IMAGE)

FORMAL_YOSYS=$(APICULA_CMD_PREFIX) yosys
FORMAL_SMTBMC=$(FORMAL_CMD_PREFIX) yosys-smtbmc
FORMAL_READ_VERILOG_PARAMS:=-sv

obj/formal.ys: $(VERILOG_FILES)
	mkdir -p obj
	rm -f $@
	echo "# this file is generated by the makefile" > $@
	for filename in $^ ; do \
	  echo "read_verilog $(FORMAL_READ_VERILOG_PARAMS) -formal -assume-asserts $$filename" >> $@ ; \
	done
	echo "prep -top counter -nordff" >> $@

obj/formal.smt2: obj/formal.ys
	echo "write_smt2 -wires " $@ >> $<
	$(FORMAL_YOSYS) $< | tee obj/yosys-formal-build.log

formal: obj/formal.smt2
	$(FORMAL_SMTBMC) $< | tee $@
	$(FORMAL_SMTBMC) -i $< | tee -a $@
