# build gowin fs using gowin eda tools

GOWIN_DOCKER_PREFIX=docker run --rm -v $(PWD):/src --workdir /src
GOWIN_DOCKER_IMAGE=davidsiaw/gwin-docker
GOWIN_CMD_PREFIX=$(GOWIN_DOCKER_PREFIX) $(GOWIN_DOCKER_IMAGE)

GWSH=$(GOWIN_CMD_PREFIX) sh -c 'cd obj; cat gowin.tcl; rm -rf impl; $$GOWINHOME/IDE/bin/gw_sh gowin.tcl'

obj/gowin_verilogfiles: $(VERILOG_FILES)
	mkdir -p obj
	echo "" > $@
	for filename in $^ ; do \
	    echo "add_file ../$$filename" >> $@ ; \
	done

obj/gowin_constraints: $(shell cat obj/args/gowin_cst)
	mkdir -p obj
	echo "" > $@
	for filename in $^ ; do \
	    echo "add_file ../$$filename" >> $@ ; \
	done

obj/gowin_settings: obj/args/device_name obj/args/gowin_class
	mkdir -p obj
	echo "" > $@
	echo "set_option -synthesis_tool gowinsynthesis" >> $@
	echo "set_option -output_base_name gowin" >> $@
	echo "set_device $(shell cat obj/args/device_name) $(shell cat obj/args/gowin_class)" >> $@
	echo "set_option -bit_format txt" >> $@
	echo "set_option -verilog_std sysv2017" >> $@
	echo "set_option -top_module $(TOP)" >> $@


obj/gowin.tcl: obj/gowin_verilogfiles obj/gowin_constraints obj/gowin_settings
	echo "# Generated by Makefile" > $@
	cat obj/gowin_verilogfiles >> $@
	cat obj/gowin_constraints >> $@
	cat obj/gowin_settings >> $@
	echo "run all" >> $@

obj/impl/pnr/gowin.fs: obj/gowin.tcl
	$(GWSH) | tee obj/gowin_eda.log

obj/gowin.fs: obj/impl/pnr/gowin.fs
	cp $< $@

gowin: obj/gowin.fs

upload_gowin: obj/gowin.fs obj/args/name
	$(OPENFPGALOADER) -b $(shell cat obj/args/name) obj/gowin.fs

.PHONY: gowin upload_gowin
