# build gowin fs using gowin eda tools

GOWIN_DOCKER_PREFIX=docker run --rm -v $(PWD):/src --workdir /src
GOWIN_DOCKER_IMAGE=davidsiaw/gwin-docker
GOWIN_CMD_PREFIX=$(GOWIN_DOCKER_PREFIX) $(GOWIN_DOCKER_IMAGE)

GOWIN_SV2VED_FILES=$(filter-out $(addsuffix /%,src),$(VERILOG_FILES))
GOWIN_V_FILES=$(filter-out $(addsuffix /%,obj/sv2ved),$(VERILOG_FILES))

GOWIN_VERILOG_FILES=$(patsubst obj/sv2ved/%.v,obj/gowinsrc/%.sv.v,$(GOWIN_SV2VED_FILES)) $(patsubst src/%.v,obj/gowinsrc/%.v,$(GOWIN_V_FILES))

GWSH=$(GOWIN_CMD_PREFIX) sh -c 'cd obj; cat gowin.tcl; rm -rf impl; $$GOWINHOME/IDE/bin/gw_sh gowin.tcl'

obj/gowinsrc/%.sv.v: obj/sv2ved/%.v obj/defines
	mkdir -p $(shell dirname "$@")
	echo "// Generated by gowin.mk" > $@
	for filename in $(shell ls obj/defines) ; do \
	    echo "\`define $$filename" >> $@; \
	done
	cat $< >> $@

obj/gowinsrc/%.v: src/%.v obj/defines
	mkdir -p $(shell dirname "$@")
	echo "// Generated by gowin.mk" > $@
	for filename in $(shell ls obj/defines) ; do \
	    echo "\`define $$filename" >> $@; \
	done
	cat $< >> $@

obj/gowinsrc/%.v: obj/sv2ved/%.v obj/defines
	mkdir -p $(shell dirname "$@")
	echo "// Generated by gowin.mk" > $@
	for filename in $(shell ls obj/defines) ; do \
	    echo "\`define $$filename" >> $@; \
	done
	cat $< >> $@

obj/gowin_verilogfiles: $(GOWIN_VERILOG_FILES)
	mkdir -p obj
	echo "" > $@
	for filename in $^ ; do \
	    echo "add_file ../$$filename" >> $@ ; \
	done

obj/gowin_constraints: $(shell cat obj/args/gowin_cst)
	mkdir -p obj
	echo "" > $@
	for filename in $^ ; do \
	    echo "add_file ../$$filename" >> $@ ; \
	done

obj/gowin_settings: obj/args/device_name obj/args/gowin_class obj/args/topmodule
	mkdir -p obj
	echo "" > $@
	echo "set_option -synthesis_tool gowinsynthesis" >> $@
	echo "set_option -output_base_name gowin" >> $@
	echo "set_device $(shell cat obj/args/device_name) $(shell cat obj/args/gowin_class)" >> $@
	echo "set_option -use_sspi_as_gpio 1" >> $@
	echo "set_option -use_mspi_as_gpio 1" >> $@
	echo "set_option -top_module $(shell cat obj/args/topmodule)" >> $@


obj/gowin.tcl: obj/gowin_verilogfiles obj/gowin_constraints obj/gowin_settings
	mkdir -p obj
	rm -f $@
	echo "# this file is generated by the makefile" > $@
	for filename in $^ ; do \
	    cat $$filename >> $@ ; \
	done
	echo "run all" >> $@

obj/impl/pnr/gowin.fs: obj/gowin.tcl
	$(GWSH) | tee obj/gowin_eda.log

obj/gowin.fs: obj/impl/pnr/gowin.fs
	cp $< $@

gowin: obj/gowin.fs

upload_gowin: obj/gowin.fs obj/args/name
	$(OPENFPGALOADER) -b $(shell cat obj/args/name) obj/gowin.fs

.PHONY: gowin upload_gowin
