VERILATOR_LINT_CMD_BASE=docker run --rm -ti -v $(PWD):/src --workdir=/src davidsiaw/ocs
VERILATOR_LINT_CMD=$(VERILATOR_LINT_CMD_BASE) verilator --lint-only
VERILATOR_LINT_PARAMS:=-Wall

obj/lint_cmd:
	mkdir -p obj
	echo "$(VERILATOR_LINT_CMD) $(VERILATOR_LINT_PARAMS) \\" > $@

obj/lint_files: $(VERILOG_FILES)
	mkdir -p obj
	rm -f $@
	ech
	for filename in $^ ; do \
	    echo "  $$filename \\" >> $@ ; \
	done

obj/lint_defines: obj/defines
	mkdir -p obj
	rm -f $@
	for filename in $(shell ls @<) ; do \
	    echo "  -D$$filename=`cat $$filename` \\" >> $@; \
	done

obj/lint.sh: obj/lint_cmd obj/lint_files obj/lint_defines
	mkdir -p obj
	rm -f $@
	echo "# this file is generated by lint.mk" > $@
	for filename in $^ ; do \
	    cat $$filename >> $@ ; \
	done

obj/lint.report: obj/lint.sh
	sh obj/lint.sh

lint: obj/lint.report

.PHONY: lint
