IVERILOG_CMD_BASE=docker run --rm -ti -v $$(pwd):/src --workdir=/src davidsiaw/ocs
IVERILOG_CMD=$(IVERILOG_CMD_BASE) iverilog
VVP_CMD=$(IVERILOG_CMD_BASE) vvp
IVERILOG_PARAMS:=

obj/wave_cmd:
	mkdir -p obj
	echo "$(IVERILOG_CMD) -DTESTBENCH $(IVERILOG_PARAMS) \\" > $@

obj/wave_files: $(VERILOG_FILES)
	mkdir -p obj
	rm -f $@
	for filename in $^ ; do \
	    echo "  -l$$filename \\" >> $@ ; \
	done

obj/wave_include_dirs: $(SRC_DIRS)
	mkdir -p obj
	rm -f $@
	for dirname in $^ ; do \
	    echo "  -I$$dirname \\" >> $@ ; \
	done

obj/wave_defines: obj/defines
	mkdir -p obj
	rm -f $@
	for filename in $(shell ls $<) ; do \
	    echo "  -D$$filename=`cat $$filename` \\" >> $@; \
	done

obj/wave.sh: obj/wave_cmd obj/wave_include_dirs obj/wave_files obj/wave_defines
	mkdir -p obj
	rm -f $@
	echo "# this file is generated by wave.mk" > $@
	for filename in $^ ; do \
	    cat $$filename >> $@ ; \
	done
	echo "-o obj/wave.out -s test"  >> $@

obj/wave.out: obj/wave.sh
	sh obj/wave.sh $(subst totee,wave,$(TEE))

wave: obj/wave.out
	$(VVP_CMD) $<

.INTERMEDIATE: obj/wave_cmd obj/wave_include_dirs obj/wave_files obj/wave_defines obj/wave.sh

.PHONY: wave
